.TH crm-backup 8  "December 15, 2014" "version 1.4.4"
.SH NAME
crm-backup \- back up the current crm config
.SH SYNOPSIS
.B crm-backup
.SH DESCRIPTION
back up current crm config to $CRMBACKUPDIR, by default /var/backups/crm
.TP
.PP
.SH EXIT STATUS
crm-backup return 0 on success or if it was unable to detect the errors.
.SH AUTHOR
Adrian Reyer (lihas (at) lihas.de)
.SH SEE ALSO
crm(1)
