#!/bin/bash

function usage {
    echo "$0 [-vDLF] -d DRBDNAME -n DRBDNUM -s SIZE"
    echo "v: verbose"
    echo "D: dummy, don't actually do anything"
    echo "d: Name of drbd"
    echo "n: Number of drbd"
    echo "s: Size of drbd"
    echo "L: Don't create LVM, just create DRBD and add Cluster resource"
    echo "F: Don't create FS, just create DRBD and add Cluster resource"
    echo "p: Enable Primary/Primary"
    echo ""
}

PRIMARYPRIMARY=n
. /etc/cluster-tools-lihas.conf

while getopts 'vDd:n:LF' OPTION; do
    case $OPTION in
	v) VERBOSE=y
	    ;;
	D) DUMMY=echo
	    ;;
	d) DRBDNAME="$OPTARG"
	   VSNAME="$DRBDNAME"
	    ;;
	n) DRBD="$OPTARG"
	    ;;
	s) SIZE="$OPTARG"
	    ;;
	L) NOLVM=y
	    ;;
	F) NOFS=y
	    ;;
	p) PRIMARYPRIMARY=y
	    ;;
	*) echo "May not happen as the first argument of getopt is not a '-'"
	    ;;
    esac
done

if [ x"$DRBDNAME" = x ]; then echo "Need -d"; exit 1; fi
if [ x"$DRBD" = x ]; then echo "Need -n"; exit 1; fi
if [ x"$SIZE" = x ] && [ x"$NOLVM" = x ]; then echo "Need -s"; exit 1; fi
DRBDPORT=$(printf "%02i" $DRBD)

create_drbd () {
    # Sorry, this uses global variables

    if [ ! -e /etc/drbd.d/vs_$VSNAME.res ]; then    
    cat <<-EOF > /etc/drbd.d/vs_$VSNAME.res
resource vs_$VSNAME {  
        protocol        C;
        syncer {
                rate    2000M;
        }
        on $HOST1 {
                device          /dev/drbd$DRBD;
                disk            /dev/$VG1/vs_$VSNAME;
                flexible-meta-disk      internal;
                address         $IP_DRBD1:77$DRBDPORT;
        }
        on $HOST2 {
                device          /dev/drbd$DRBD;
                disk            /dev/$VG2/vs_$VSNAME;
                flexible-meta-disk      internal;
                address         $IP_DRBD2:77$DRBDPORT;
        }
}
EOF
    else
	echo "/etc/drbd.d/vs_$VSNAME.res already exists"
	exit 1
    fi
}

# create_lvm
if [ x"$NOLVM" = xy ]; then
  echo "Skipping LVM creation due to -L"
else
  $DUMMY create_lvm
fi

# create_drbd
$DUMMY create_drbd

# create_fs
if [ x"$NOFS" = xy ]; then
  echo "Skipping FS creation due to -F"
else
  $DUMMY create_fs
fi
